# Generated by Django 5.1.6 on 2025-02-12 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d8255d6b-209a-43e7-8354-18b5dd6fb898'), unique=True),
        ),
    ]
