# Generated by Django 5.1.6 on 2025-02-12 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.UUID('1b0e80a2-13c3-4e47-b01e-b0ffacc2691b'), unique=True),
        ),
    ]
