# Generated by Django 5.1.6 on 2025-02-12 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.UUID('7509794d-2f87-46cd-a8c8-1aadd9db351e'), unique=True),
        ),
    ]
