# Generated by Django 5.1.6 on 2025-02-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('league', models.CharField(choices=[('L', 'Laliga'), ('P', 'Premier'), ('C', 'Calcio'), ('B', 'Bundesliga')], max_length=1)),
                ('shield', models.ImageField(blank=True, default='teams/shields/default.png', null=True, upload_to='teams/shields')),
            ],
        ),
    ]
