# Generated by Django 5.1.6 on 2025-02-12 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.UUIDField(default=uuid.UUID('786696e2-1616-49ce-9e89-f841dee49c03'), unique=True),
        ),
    ]
