# Generated by Django 5.1.6 on 2025-02-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defense'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('birth_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('photo', models.ImageField(blank=True, default='players/photos/default.png', null=True, upload_to='players/photos')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
        ),
    ]
